### PR TITLE
Bux Fixes and Additional Colors

### PR DESCRIPTION
**Pull request by AustinTSchaffer**
- Swapped custom complex number library for builtins
- Added a new constant for controlling the max number of iterations
- Added a function that controls the color of the output

### CODE REVIEW

**Comment by AustinTSchaffer** [comment]
Closes #1

**Comment by AustinTSchaffer** [comment]
@TFC-343, I saw that you offered to give me access to your repo. I'd definitely advise against giving people that you don't know (and can't reasonably trust) access to your personal repositories, so I've declined the invitation. Below is an article on how to merge a GitHub pull request that targets a repository that you own or otherwise administer, along with an article on GitHub PRs in general.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by TFC-343** [comment]
would you like to add your name to the readme?
as you've done quite a bit for my code .

**Comment by AustinTSchaffer** [comment]
@TFC-343, lol, nah only if you feel inclined to add something 🙂. Don't go out of your way though. I do these kinds of things to help teach Python, Git, and do some light code review. I've also never generated a Mandelbrot on my own hardware, so it was nice to tick that one off too.

Might be good to update the README anyway to make it accurate, maybe including a screenshot of the result.

**Pull request merged**
